name: fugu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - decorator==4.4.2
  - future==0.18.2
  - greenlet==0.4.16
  - networkx==2.4
  - numpy=1.15.*
  - pandas==1.0.5
  - python-dateutil==2.8.1
  - pytz==2020.1
  - six==1.15.0
  - msgpack-python=1.0.*
  - pytorch=1.5.0
  - furo
  - sphinx_rtd_theme
  - sphinx
  - matplotlib>=2.2.2
  - notebook
  - nb_conda_kernels
  - pytest
  - coverage
  - isort
  - black
  - pip
  - scipy
  - pandas=1.5.*
